### ISSUE TITLE
Calling template generates a sequence

### ISSUE THREAD

**Issue by JJ** [chloekek/Template-Classic#1]
This

```
use Template::Classic;

my &render-list := template :($title), q:to/HTML/;
        <%= $title %>
        HTML

say render-list( "Hey" );
```
generates a Seq, not a Str. The elements of the sequence are not entirely clear:

```
use Template::Classic;

my &render-list := template :($title), q:to/HTML/;
Say <%= $title %>
HTML

my @seq = render-list( "Hey" );

for ^3 -> $i {
    say $i, " → ", @seq[$i];
}
```

This prints:

```
0 → Say 
1 → Hey
2 → 

```

It's also a lazy sequence, so it's not possible to just "join" it to the result. Not clear if this is because of the type of signature I'm using...

**Comment by zopsicle** [comment]
Yes it’s supposed to return a lazy sequence so that you can stream the result. I guess we could add an optional flag to the template to make it return a string instead.

```raku
my &render-list := template :($title), q:to/HTML/, :Str;
```

**Comment by JJ** [comment]
The problem is that the lazy sequence is organized in a rather weird way. After doing the change you suggested in #2 now it goes like this:
```
0
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test page</title>
<link rel='stylesheet' id='style-css'  href='raku-recipes.css' type='text/css'
      media='all' />
</head>
<body>
<!-- This is a Template::Classic template -->


1
<h1>Rice pudding</h1>
<p>A sweet and tangy, as well as nutritious, recipe, that can be taken also for breakfast. </p>
2
&lt;h1&gt;Rice pudding&lt;/h1&gt;
&lt;p&gt;A sweet and tangy, as well as nutritious, recipe, that can be taken also for breakfast. &lt;/p&gt;
3


</body>
</html>
```
So, first and last element of the sequence are parte of the template, in the middle there's the substituted content and then the escaped substituted content?

**Comment by zopsicle** [comment]
You have to use <%, not <%=, when using take. <%= … %> is short for <% take(escape(…)) %>

**Comment by JJ** [comment]
Hey, looks fine. Thanks!
(some comments about this in the documentation would be awesome)
